import smtplib



def switch_alpha(argument):
    date_dict={'$':'-','0':0,'a':1,'b':2,'c':3,'d':4,'e':5,'f':6,'g':7,'h':8,'i':9,'j':10,'k':11,'l':12,'m':13
        ,'n':14,'o':15,'p':16,'q':17,'r':18,'s':19,'t':20,'u':21,'v':22,'w':23,'x':24,'y':25,'z':26,'@':'@','#':'#','%':'%','*':'*' }

    date_dict.get(argument, "invalid Licence argument...")
    return (date_dict.get(argument))



password='Your_password type according to switch_alpha function value keys in order to keep it secure'

x = 0
dp = ''
while (x < len(password)):
    dp = str(switch_alpha(str(password[x]))) + str(dp)
    x += 1
final_pass=dp[::-1]

gmailaddress ="Your_mail_id"
gmailpassword =str(final_pass)


mailto=[]
mailto.append("yyyyyyyyyyyy@gmail.com")
mailto.append("xxxxxxxxxx@gmail.com")
mailto.append("zzzzzzzzzzzzz@gmail.com")
mailto.append("kkkkkkkkkkkkk@gmail.com")


i=0
while (i<len(mailto)):
    msg ="I am Vinayak ...this massage is generated by his python code...Hi there...smile please...his code worked.."
    mailServer = smtplib.SMTP('smtp.gmail.com' , 587)
    mailServer.starttls()
    mailServer.login(gmailaddress , gmailpassword)
    mailServer.sendmail(gmailaddress, mailto[i] , msg)
    print(" \n Sent!")
    i+=1
mailServer.quit()